import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google';

const myfont  = DM_Sans({ subsets: ['latin'], weight: ['500']})

export const metadata: Metadata = {
  title: "Jordii's Portfolio",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={myfont.className}>{children}</body>
    </html>
  )
}
