import type { Metadata } from 'next'
import { Manrope } from 'next/font/google';

const myfont  = Manrope({ subsets: ['latin'], weight: ['500']})

export const metadata: Metadata = {
  title: "Jordi Bru",
  description: 'Generated by create next app',
  icons: {
    icon: { url: '/favicon.ico', type: 'image/ico' }
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={myfont.className}>{children}</body>
    </html>
  )
}
